CREATE DATABASE IF NOT EXISTS temperatures;
CREATE DATABASE IF NOT EXISTS apidocuments;
CREATE DATABASE IF NOT EXISTS poker;
CREATE DATABASE IF NOT EXISTS inspiration;
CREATE DATABASE IF NOT EXISTS pmt;
